import "@/styles/globals.css";
import Navbar from "@/components/Navbar";

import { Inter, Balsamiq_Sans } from "next/font/google";
import MainContainer from "@/components/MainContainer";
// import { SessionProvider } from "next-auth/react";
// import AuthProvider from "@/components/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const balsamiq = Balsamiq_Sans({
  weight: ["400", "700"],
  variable: "--balsamiq-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans  ${balsamiq.variable}`}>
        <div>
          <Navbar />
          <div className="container mx-auto">
            <MainContainer>{children}</MainContainer>
          </div>
        </div>
      </body>
    </html>
  );
}
